### ISSUE TITLE
[REQUEST] Alt Links

### ISSUE THREAD

**Issue by Dentamon** [3kh0/eaglercraft#1]
Hey 3k, it's me, Madmon.
So basically, your site is blocked for me, and it is too slow on a proxy, so I am wondering if you can make alts to it, that would be really helpful!  github.io links don't work, so if you can make an unblocked link, I would really appreciate it.

**Comment by 3kh0** [comment]
Please join the discord for that type of question.
- https://discord.gg/3kh0

**Comment by Dentamon** [comment]
Understood, thanks.
